nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Authorization", "Accept"]
        max_age: 3600
    paths:
        "^/":
            origin_regex: false
            allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]
            allow_headers: ["Authorization", "Accept"]
            max_age: 3600
