services:
    database:
        container_name: meeio-database
        image: postgres:${POSTGRES_VERSION:-16.4}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-meeio}
            POSTGRES_USER: ${POSTGRES_USER:-user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        volumes:
            - pgdata:/var/lib/postgresql/data:rw

    pgadmin:
        image: dpage/pgadmin4:8.11
        container_name: meeio-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-example@mail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
        depends_on:
            - database
        ports:
            - 8081:80

    mailer:
        image: rnwood/smtp4dev
        container_name: meeio-mailer
        ports:
            - 8082:80
            - 2525:25

    api:
        container_name: meeio-api
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - database
            - mailer

volumes:
    pgdata:
