version: "3.8"

services:
    database:
        container_name: flashcard-database
        image: postgres:16.4-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:8.11
        container_name: flashcard-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: example@mail.com
            PGADMIN_DEFAULT_PASSWORD: password
        depends_on:
            - database
        ports:
            - 8081:80

    mailer:
        image: rnwood/smtp4dev
        container_name: flashcard-mailer
        ports:
            - 8082:80
            - 2525:25

    api:
        container_name: flashcard-api
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - database
            - mailer

volumes:
    pgdata:
