version: "3.8"

services:
    database:
        command: --max-allowed-packet=64MB
        container_name: flashcard-database
        image: mariadb
        ports:
            - 3306:3306 # To access the database through the mysql extension in vscode
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: flashcard
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - data:/var/lib/mariadb
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: flashcard-mail
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8082:80
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: flashcard-phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        depends_on:
            - database
        networks:
            - dev
        ports:
            - 8081:80

    api:
        container_name: flashcard-api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VARIANT=8.2.8-apache
        ports:
            - 8080:80
        volumes:
            - ../:/var/www
        networks:
            - dev
        depends_on:
            - database

volumes:
    data:

networks:
    dev:
