version: "3.8"

services:
    database:
        command: --max-allowed-packet=64MB
        container_name: flashcard-database
        image: mariadb
        ports:
            - 3306:3306 # To access the database through the mysql extension in vscode
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: flashcard
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - data:/var/lib/mariadb
        networks:
            - dev

    mailer:
        image: rnwood/smtp4dev
        container_name: flashcard-mail
        ports:
            - 8082:80
            - 2525:25
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: flashcard-phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        depends_on:
            - database
        networks:
            - dev
        ports:
            - 8081:80

    nginx:
        image: nginx:alpine3.18
        ports:
            - 80:80
        volumes:
            - ..:/var/www
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - php

    php:
        container_name: flashcard-php
        build:
            dockerfile: Dockerfile
        volumes:
            - ..:/var/www
        networks:
            - dev
        depends_on:
            - database

volumes:
    data:

networks:
    dev:
