version: "3.8"

services:
    database:
        command: --max-allowed-packet=64MB
        container_name: flashcard-database
        image: mariadb
        ports:
            - 3306:3306 # To access the database through the mysql extension in vscode
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: flashcard
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - data:/var/lib/mariadb

    mailer:
        image: rnwood/smtp4dev
        container_name: flashcard-mailer
        ports:
            - 8082:80
            - 2525:25

    adminer:
        image: adminer
        container_name: flashcard-adminer
        depends_on:
            - database
        ports:
            - 8081:8080

    nginx:
        image: nginx:alpine-3.18
        container_name: flashcard-nginx
        ports:
            - 80:80
        volumes:
            - project:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - php

    php:
        container_name: flashcard-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - project:/var/www/html
        ports:
            - 9000:9000
        depends_on:
            - database

volumes:
    data:
    project:
