name: Security Checker

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]
    workflow_call:

jobs:
    php:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true

        steps:
            - uses: actions/checkout@v4

            - name: Validate composer.json and composer.lock
              run: composer validate

            - uses: actions/cache@v4
              id: cache-db
              with:
                  path: ~/.symfony/cache
                  key: db

            - uses: symfonycorp/security-checker-action@v3

            - name: Display the vulnerabilities as JSON
              run: echo ${{ steps.security-check.outputs.vulns }}
